/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Coversor;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ConversorGrados extends javax.swing.JPanel {

    /**
     * Creates new form ConversorGrados
     */
    
    double GraCelius, GraKelvin, GraFarengei;
    
    public ConversorGrados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textCelcius = new javax.swing.JTextField();
        textFarengei = new javax.swing.JTextField();
        textKelvin = new javax.swing.JTextField();
        btnCalculador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        textCelcius.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCelciusActionPerformed(evt);
            }
        });
        textCelcius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCelciusKeyTyped(evt);
            }
        });

        textFarengei.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        textFarengei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFarengeiActionPerformed(evt);
            }
        });

        textKelvin.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        btnCalculador.setBackground(new java.awt.Color(255, 102, 102));
        btnCalculador.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnCalculador.setText("Calcular");
        btnCalculador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculadorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("F");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("K");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("° C");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(textCelcius)
                    .addComponent(textFarengei)
                    .addComponent(textKelvin)
                    .addComponent(btnCalculador, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalculador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFarengei, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFarengeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFarengeiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFarengeiActionPerformed

    private void btnCalculadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculadorActionPerformed
        // TODO add your handling code here:
        if(textCelcius.getText().length()>0){
            GraCelius = Double.parseDouble(textCelcius.getText());
            GraFarengei = (GraCelius* 1.8) + 32;
            GraKelvin = GraCelius + 237.15;
           this.textFarengei.setText(Double.toString(GraFarengei));
           this.textKelvin.setText(Double.toString(GraKelvin));          
            
        }else{
            JOptionPane.showMessageDialog(this, "Error, caja vacia...!");
        }
    }//GEN-LAST:event_btnCalculadorActionPerformed

    private void textCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCelciusActionPerformed

    private void textCelciusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCelciusKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        //codi ascii
        boolean numero = key>=48 && key <=57;
        boolean signo = key>=45 && key<=45;
        if(!numero && !signo){
            evt.consume();
        }
    }//GEN-LAST:event_textCelciusKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textCelcius;
    private javax.swing.JTextField textFarengei;
    private javax.swing.JTextField textKelvin;
    // End of variables declaration//GEN-END:variables
}
