/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Coversor;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ConversorDivisa extends javax.swing.JPanel {

    String[] currencyUnit = {
        "unit",
        "Boliviano",
        "Dólar canadiense",
        "Dólar estadounidense",        
        "Euro",
        "Peso argentino",
        "Peso chileno",
        "Peso colomiano",                
        "Peso mexicado",
        "Real brasileño",
        
        
    };
    //modena de referencia dolar estadunidense (USD)
        double USD = 1;
        double USD_Bs = 661.16; 
        double USD_CAD = 1.34;
        double USD_EUR = 0.91;
        double USD_ARS = 228.53;
        double USD_CLP = 788.62;
        double USD_COP = 4549.75;
        double USD_MXM = 17.54;
        double USD_BRL = 4.94;
    
    
    public ConversorDivisa() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divpanel = new javax.swing.JPanel();
        TextUno = new javax.swing.JTextField();
        TextDos = new javax.swing.JTextField();
        btnConvertidor = new javax.swing.JButton();
        firstCountry = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        secondCountry = new javax.swing.JComboBox<>();
        firstUnit = new javax.swing.JLabel();
        secondUnit = new javax.swing.JLabel();

        TextUno.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        TextUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUnoActionPerformed(evt);
            }
        });
        TextUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextUnoKeyTyped(evt);
            }
        });

        TextDos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        TextDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDosActionPerformed(evt);
            }
        });

        btnConvertidor.setBackground(new java.awt.Color(204, 255, 204));
        btnConvertidor.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnConvertidor.setText("Calcular");
        btnConvertidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertidorActionPerformed(evt);
            }
        });

        firstCountry.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        firstCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Bs", "CAD", "USD", "EUR", "ARS", "CLP", "COP", "MXM", "BRL", " " }));
        firstCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCountryActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        secondCountry.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        secondCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Bs", "CAD", "USD", "EUR", "ARS", "CLP", "COP", "MXM", "BRL", " " }));
        secondCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondCountryActionPerformed(evt);
            }
        });

        firstUnit.setText("Unit");

        secondUnit.setText("Unit");

        javax.swing.GroupLayout divpanelLayout = new javax.swing.GroupLayout(divpanel);
        divpanel.setLayout(divpanelLayout);
        divpanelLayout.setHorizontalGroup(
            divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConvertidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(divpanelLayout.createSequentialGroup()
                        .addGroup(divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextUno)
                                .addComponent(TextDos, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstUnit)
                            .addGroup(divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(firstCountry, 0, 150, Short.MAX_VALUE)
                                .addComponent(secondCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(secondUnit))))
                .addGap(34, 34, 34))
        );
        divpanelLayout.setVerticalGroup(
            divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divpanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextUno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(firstCountry))
                .addGap(4, 4, 4)
                .addComponent(firstUnit)
                .addGap(18, 18, 18)
                .addGroup(divpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextDos)
                    .addComponent(secondCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondUnit)
                .addGap(14, 14, 14)
                .addComponent(btnConvertidor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDosActionPerformed

    private void TextUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUnoActionPerformed

    private void firstCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCountryActionPerformed
        // TODO add your handling code here:
        int position = firstCountry.getSelectedIndex();
        firstUnit.setText(currencyUnit[position]);
    }//GEN-LAST:event_firstCountryActionPerformed

    private void secondCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondCountryActionPerformed
        // TODO add your handling code here:
        int position = secondCountry.getSelectedIndex();
        secondUnit.setText(currencyUnit[position]);
    }//GEN-LAST:event_secondCountryActionPerformed

    private void btnConvertidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertidorActionPerformed
        // TODO add your handling code here:

        if(TextUno.getText().length()>0){
            double amountToChange = Double.parseDouble(TextUno.getText());
            double amountInPounds = 0.0;
            switch (firstCountry.getSelectedItem().toString()) {
            case "ARS": amountInPounds = amountToChange / USD_ARS;break;
            case "BRL": amountInPounds = amountToChange / USD_BRL;break;
            case "Bs": amountInPounds = amountToChange / USD_Bs;break;
            case "CAD": amountInPounds = amountToChange / USD_CAD;break;
            case "CLP": amountInPounds = amountToChange / USD_CLP;break;
            case "COP": amountInPounds = amountToChange / USD_COP;break;
            case "EUR": amountInPounds = amountToChange / USD_EUR;break;
            case "MXM": amountInPounds = amountToChange / USD_MXM;break;
            case "USD" : amountInPounds = amountToChange / USD; break;
        }
        double amountChanged = 0.0;
        switch (secondCountry.getSelectedItem().toString()) {
            case "ARS": amountChanged = amountInPounds * USD_ARS;break;
            case "BRL": amountChanged = amountInPounds * USD_BRL;break;
            case "Bs": amountChanged = amountInPounds * USD_Bs;break;
            case "CAD": amountChanged = amountInPounds * USD_CAD;break;
            case "CLP": amountChanged = amountInPounds * USD_CLP;break;
            case "COP": amountChanged = amountInPounds * USD_COP;break;
            case "EUR": amountChanged = amountInPounds * USD_EUR;break;
            case "MXM": amountChanged = amountInPounds * USD_MXM;break;

        }
        
        //String value = String.format("%.2f",amountChanged currencyUnit);
        String value = String.format("%.2f",amountChanged);
        TextDos.setText(value);
        }else{
            JOptionPane.showMessageDialog(this, "Error, caja vacia...!");
        }
    }//GEN-LAST:event_btnConvertidorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        firstCountry.setSelectedIndex(0);
        secondCountry.setSelectedIndex(0);
        TextUno.setText(null);
        TextDos.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TextUnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextUnoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        //codi ascii
        boolean numero = key>=48 && key <=57;
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_TextUnoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDos;
    private javax.swing.JTextField TextUno;
    private javax.swing.JButton btnConvertidor;
    private javax.swing.JPanel divpanel;
    private javax.swing.JComboBox<String> firstCountry;
    private javax.swing.JLabel firstUnit;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> secondCountry;
    private javax.swing.JLabel secondUnit;
    // End of variables declaration//GEN-END:variables
}
